"""remove unique constraint from agent_api_key

Revision ID: abe4f5a99a28
Revises: efd0c3dcead3
Create Date: 2025-07-12 12:47:38.538079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abe4f5a99a28'
down_revision: Union[str, Sequence[str], None] = 'efd0c3dcead3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('agent_api_key'), table_name='dify_agent')
    op.drop_constraint(op.f('dify_agent_ibfk_1'), 'dify_agent', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('dify_agent_ibfk_1'), 'dify_agent', 'user', ['belong_user_account'], ['user_account'])
    op.create_index(op.f('agent_api_key'), 'dify_agent', ['agent_api_key'], unique=True)
    # ### end Alembic commands ###
