"""Initial migration

Revision ID: efd0c3dcead3
Revises: 
Create Date: 2025-07-12 11:25:18.812595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efd0c3dcead3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=250), nullable=False),
    sa.Column('user_account', sa.String(length=255), nullable=False),
    sa.Column('user_password', sa.String(length=255), nullable=False),
    sa.Column('user_VIP', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('user_VIP_deadline', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('owner_agents', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_account'),
    sa.UniqueConstraint('user_name')
    )
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_table('dify_agent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_name', sa.String(length=255), nullable=False),
    sa.Column('agent_describe', sa.Text(), nullable=True),
    sa.Column('agent_url', sa.String(length=255), nullable=False),
    sa.Column('agent_api_key', sa.String(length=500), nullable=False),
    sa.Column('agent_Content_Type', sa.String(length=50), nullable=True),
    sa.Column('response_mode', sa.String(length=50), nullable=True),
    sa.Column('user', sa.String(length=255), nullable=False),
    sa.Column('auto_generate_name', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('belong_user_account', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['belong_user_account'], ['user.user_account'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_api_key'),
    sa.UniqueConstraint('user')
    )
    op.create_index(op.f('ix_dify_agent_id'), 'dify_agent', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dify_agent_id'), table_name='dify_agent')
    op.drop_table('dify_agent')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
